### ISSUE TITLE
SDK version issue

### ISSUE THREAD

**Issue by AlaaEldeenYsr** [Apple-Actions/upload-testflight-build#72]
This app was built with the iOS 17.5 SDK. All iOS and iPadOS apps must be built with the iOS 18 SDK or later, included in Xcode 16 or later, in order to be uploaded to App Store Connect or submitted for distribution

```yaml
on:
  push:
    branches:
      - staging

name: Build and Release Thabat iOS App

jobs:
  build:
    name: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: cedvdb/action-flutter-build-ios@v1
        with:
          build-cmd: flutter build ipa --release --flavor staging --dart-define=ENV=staging --export-options-plist=ios/config/staging/ExportOptions.plist
          certificate-base64: ${{ secrets.IOS_CERTIFICATE }}
          certificate-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          provisioning-profile-base64: ${{ secrets.PROVISIONING_PROFILE_STAGING_THABAT }}
          keychain-password: ${{ secrets.IOS_GITHUB_KEYCHAIN_PASSWORD }}

      - name: Upload to TestFlight
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: build/ios/ipa/thabat.ipa
          issuer-id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          api-key-id: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          api-private-key: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}

```

```
Run apple-actions/upload-testflight-build@v1
/usr/bin/xcrun altool --output-format xml --upload-app --file build/ios/ipa/thabat.ipa --type ios --apiKey *** --apiIssuer ***
2025-04-27 15:54:56.802 *** Error: ERROR: [ContentDelivery.Uploader] Validation failed (409) SDK version issue. This app was built with the iOS 17.5 SDK. All iOS and iPadOS apps must be built with the iOS 18 SDK or later, included in Xcode 16 or later, in order to be uploaded to App Store Connect or submitted for distribution. (ID: 0049db94-9a74-4665-8af2-579db9728272)
2025-04-27 15:55:16.556  INFO: [ContentDelivery.Uploader] 
=============
UPLOAD FAILED with 1 error.
=============
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>os-version</key>
	<string>14.7.5</string>
	<key>product-errors</key>
	<array>
		<dict>
			<key>code</key>
			<integer>409</integer>
			<key>message</key>
			<string>Validation failed</string>
			<key>userInfo</key>
			<dict>
				<key>NSLocalizedDescription</key>
				<string>Validation failed</string>
				<key>NSLocalizedFailureReason</key>
				<string>SDK version issue. This app was built with the iOS 17.5 SDK. All iOS and iPadOS apps must be built with the iOS 18 SDK or later, included in Xcode 16 or later, in order to be uploaded to App Store Connect or submitted for distribution. (ID: 0049db94-9a74-4665-8af2-579db9728272)</string>
				<key>NSUnderlyingError</key>
				<string>Error Domain=IrisAPI Code=-19241 "Validation failed" UserInfo={status=409, detail=SDK version issue. This app was built with the iOS 17.5 SDK. All iOS and iPadOS apps must be built with the iOS 18 SDK or later, included in Xcode 16 or later, in order to be uploaded to App Store Connect or submitted for distribution., id=0049db94-9a74-4665-8af2-579db9728272, code=STATE_ERROR.VALIDATION_ERROR, title=Validation failed, NSLocalizedFailureReason=SDK version issue. This app was built with the iOS 17.5 SDK. All iOS and iPadOS apps must be built with the iOS 18 SDK or later, included in Xcode 16 or later, in order to be uploaded to App Store Connect or submitted for distribution., NSLocalizedDescription=Validation failed}</string>
				<key>iris-code</key>
				<string>STATE_ERROR.VALIDATION_ERROR</string>
			</dict>
		</dict>
	</array>
	<key>tool-path</key>
	<string>/Applications/Xcode_15.4.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/Frameworks/AppStoreService.framework</string>
	<key>tool-version</key>
	<string>7.006.15006</string>
</dict>
</plist>
Error: The process '/usr/bin/xcrun' failed with exit code 1
```
