### ISSUE TITLE
Error: Missing download info for apple-actions/upload-testflight-build@v3

### ISSUE THREAD

**Issue by AlaaEldeenYsr** [Apple-Actions/upload-testflight-build#75]
I'm facing an error at the beginning of workflow run ```Error: Missing download info for apple-actions/upload-testflight-build@v3```
And when I try to change the ```v3``` to ```v1``` it works fine

![Image](https://github.com/user-attachments/assets/229ce831-7780-4158-8383-6386af2cfc44)

```
on:
  push:
    branches:
      - staging

name: Build and Release Thabat iOS App

jobs:
  build:
    name: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: cedvdb/action-flutter-build-ios@v1
        with:
          build-cmd: flutter build ipa --release --flavor staging --dart-define=ENV=staging --export-options-plist=ios/config/staging/ExportOptions.plist
          certificate-base64: ${{ secrets.IOS_CERTIFICATE }}
          certificate-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          provisioning-profile-base64: ${{ secrets.PROVISIONING_PROFILE_STAGING_THABAT }}
          keychain-password: ${{ secrets.IOS_GITHUB_KEYCHAIN_PASSWORD }}

      - name: Upload to TestFlight
        uses: apple-actions/upload-testflight-build@v3
        with:
          app-path: build/ios/ipa/thabat.ipa
          issuer-id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          api-key-id: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          api-private-key: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}

```
